import type { Product } from './types';

const PRODUCTS: Product[] = [
  // --- SKINCARE E TRATAMENTOS FACIAIS ---

  {
    id: "medicube-forever-cherry-ager-booster",
    name: "Medicube x Forever Cherry Age-R Booster (Edição Especial)",
    jpName: "Medicube x Forever Cherry Age-R Booster (Edição Especial)",
    description: "Dispositivo facial multifuncional com escova vibratória rosa em edição especial com laço. Ideal para limpeza profunda, esfoliação e melhor absorção de séruns.",
    priceBRL: 189.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/Hx8b2BgB/IMG-0671.jpg",
    rating: 5.0,
    reviewsCount: 12,
    department: "Beleza, Higiene e Saúde",
    category: "Acessórios e Dispositivos Estéticos",
    stock: 5
  },
  {
    id: "femimore-glutathione-bubble-soap",
    name: "Femimore Glutathione Bubble Soap",
    jpName: "Femimore Glutathione Bubble Soap",
    description: "Sabonete em espuma com Glutathione. Proporciona limpeza suave, ajuda no controle de oleosidade, odor e promove clareamento leve da pele.",
    priceBRL: 110.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/sf9MRtwB/femimore.jpg",
    rating: 4.7,
    reviewsCount: 45,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 20
  },
  {
    id: "mise-en-scene-perfect-serum-original",
    name: "Mise en Scène Perfect Serum Original",
    jpName: "Mise en Scène Perfect Serum Original",
    description: "Sérum capilar coreano queridinho. Proporciona brilho intenso, hidratação, controle de frizz e proteção térmica aos fios.",
    priceBRL: 75.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/XYhJ8378/serun.webp",
    rating: 4.9,
    reviewsCount: 182,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 15
  },

  {
    id: "anessa-perfect-uv-milk-sachet",
    name: "Anessa Perfect UV Sunscreen Skincare Milk (Sachet - 60ml)",
    jpName: "アネッサ パーフェクトUV スキンケアミルク",
    description: "Protetor solar facial/corporal em leite (milk). Fator de Proteção: SPF 50+ PA++++. Muito resistente à água e suor, textura leve, acaba seco e não deixa branco. Um dos protetores solares mais vendidos no Japão.",
    priceBRL: 189.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/QtwJjnp6/images-(3).jpg",
    rating: 4.9,
    reviewsCount: 345,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 30
  },
  {
    id: "anessa-perfect-uv-milk-normal",
    name: "Anessa Perfect UV Sunscreen Skincare Milk (60ml)",
    jpName: "アネッサ パーフェクトUV スキンケアミルク",
    description: "Protetor solar facial/corporal em leite (milk). Fator de Proteção: SPF 50+ PA++++. Mesma linha premium da Anessa, com alta proteção, skincare integrado (hidrata enquanto protege) e excelente performance em dias quentes/molhados.",
    priceBRL: 199.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/1XDwsRR9/images-(4).jpg",
    rating: 5.0,
    reviewsCount: 412,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 25
  },
  {
    id: "dr-althea-345-relief-cream",
    name: "Dr. Althea 345 Relief Cream",
    jpName: "Dr. Althea 345 リリーフ クリーム",
    description: "Creme calmante e hidratante para todos os tipos de pele. Contém Ceramidas, Niacinamida, Centella e Ácido Hialurônico. Excelente para pele sensível, irritada ou com barreira danificada.",
    priceBRL: 199.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/BZ75z3fb/athea.jpg",
    rating: 4.9,
    reviewsCount: 112,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 20
  },
  {
    id: "vt-rejuvenating-lifting-eye-cream",
    name: "VT Rejuvenating Lifting Eye Cream",
    jpName: "VT リジュベナイティング リフティング アイクリーム",
    description: "Creme para olhos com efeito lifting da VT Cosmetics. Ajuda a reduzir rugas, firmar a pele e melhorar olheiras.",
    priceBRL: 176.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/fRmxk0t8/vt.jpg",
    rating: 4.8,
    reviewsCount: 85,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 15
  },
  {
    id: "axis-y-vegan-collagen-eye-serum",
    name: "AXIS-Y Vegan Collagen Eye Serum",
    jpName: "AXIS-Y ヴィーガン コラーゲン アイ セラム",
    description: "Sérum vegano para olhos com colágeno vegetal, peptídeos e ácido hialurônico. Possui roller metálico para massagem refrescante.",
    priceBRL: 176.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/k41SLQZ0/axis.jpg",
    rating: 4.9,
    reviewsCount: 98,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 18
  },
  {
    id: "anti-signal-wrinkle-hunter-eye-cream",
    name: "Anti-Signal Wrinkle Hunter Eye Cream",
    jpName: "アンチシグナル リンクルハンター アイクリーム",
    description: "Creme japonês anti-rugas para olhos com Retinol e Niacinamida. Focado em reduzir linhas finas e melhorar a firmeza.",
    priceBRL: 99.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/mZnMwS7m/qoo.avif",
    rating: 4.7,
    reviewsCount: 64,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 25
  },
  {
    id: "ckd-retino-collagen-guasha-serum",
    name: "CKD Guaranteed Retino Collagen Guasha Lifting Serum (40 ml)",
    jpName: "CKD レチノコラーゲン グアシャ セラム",
    description: "Inovador sérum anti-flacidez com colágeno de baixo peso molecular (300Da) e Retinal encapsulado. Possui uma ponteira Guasha de aço integrada ao tubo, permitindo massagear e esculpir o contorno facial enquanto aplica o produto para um efeito lifting imediato.",
    priceBRL: 240.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/T1W7FPXd/44c88aaa91c275254a2890625d122bf7.jpg",
    rating: 4.9,
    reviewsCount: 45,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 20
  },
  {
    id: "medicube-placenta-capsule-serum",
    name: "Medicube Placenta Capsule Serum (25 ml)",
    jpName: "メディキューブ プラセンタ カプセル セラム",
    description: "Tratamento inovador de alta performance em gel repleto de microcápsulas activas. Combina os benefícios regenerativos da placenta com a ação iluminadora e protetora de um complexo de vitaminas.",
    priceBRL: 220.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/YSHCQS69/71x-Xh-HGE5t-L-AC-UF894-1000-QL80.jpg",
    rating: 4.9,
    reviewsCount: 42,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 15
  },
  {
    id: "medicube-hyaluronic-multi-peptide-serum",
    name: "Medicube Hyaluronic Multi Peptide Serum (30 ml)",
    jpName: "メディキューブ ヒアルロン マルチペプチド",
    description: "Um super booster de hidratação e sustentação cutânea. Fórmula une alta concentração de ácido hialurônico a um complexo robusto de peptídeos.",
    priceBRL: 175.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/kXSCwmXq/XXL-p0217815188.webp",
    rating: 4.8,
    reviewsCount: 65,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 20
  },
  {
    id: "medicube-pdrn-pink-collagen-exosome-shot",
    name: "Medicube PDRN Pink Collagen Exosome Shot 7500 (30 ml)",
    jpName: "メディキューブ PDRN ピンクコラーゲン エクソソーム",
    description: "Sérum intensivo combinando PDRN (DNA de Salmão), exossomos e colágeno para regeneração profunda.",
    priceBRL: 175.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/pXKTr8jf/medicube-serum-pink-pdrn-colag-exosso-shot-7500-30ml-28791.jpg",
    rating: 4.9,
    reviewsCount: 54,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 18
  },
  {
    id: "medicube-red-cleansing-foam",
    name: "Medicube Red Cleansing Foam",
    jpName: "メディキューブ レッド クレンジング フォーム",
    description: "Espuma de limpeza suave com ingredientes naturais que remove completamente maquiagem e impurezas.",
    priceBRL: 80.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/rmGLhFqk/medicube-red-line-cleansing-foam.jpg",
    rating: 4.8,
    reviewsCount: 203,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 25
  },
  {
    id: "cosrx-advanced-snail-96-mucin-power-essence",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    jpName: "COSRX アドバンスド スネイル ムチン パワー エッセンス",
    description: "Essência hidratante com 96% de muco de caracol. Proporciona hidratação profunda, regeneração e brilho natural.",
    priceBRL: 120.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/zGkRWxcM/cosrx-advanced-snail-96-mucin-power-essence.jpg",
    rating: 4.9,
    reviewsCount: 567,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 30
  },
  {
    id: "pyunkang-yul-nutrition-cream",
    name: "Pyunkang Yul Nutrition Cream",
    jpName: "ピョンガン ユル ニュートリション クリーム",
    description: "Creme nutritivo com ingredientes calmantes naturais. Ideal para pele seca ou danificada.",
    priceBRL: 95.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/L6q8y9vZ/pyunkang-yul-nutrition-cream.jpg",
    rating: 4.8,
    reviewsCount: 289,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 22
  },
  {
    id: "isntree-hyaluronic-toner-plus",
    name: "ISNTREE Hyaluronic Toner Plus",
    jpName: "ISNTREE ヒアルロン トナー プラス",
    description: "Tônico com 5 tipos de ácido hialurônico. Hidrata, prepara a pele para absorção de séruns e cremes.",
    priceBRL: 85.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CqxQVwZ/isntree-hyaluronic-toner-plus.jpg",
    rating: 4.9,
    reviewsCount: 412,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 28
  },
  {
    id: "purito-deep-sea-pure-water-cream",
    name: "Purito Deep Sea Pure Water Cream",
    jpName: "プリート ディープシー ピュア ウォータークリーム",
    description: "Creme leve com água profunda do mar. Hidrata sem deixar oleoso, perfeito para climas quentes.",
    priceBRL: 90.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/xTYYR3vc/purito-deep-sea-pure-water-cream.jpg",
    rating: 4.7,
    reviewsCount: 178,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 19
  },
  {
    id: "some-by-mi-aha-bha-pha-30-days-miracle-serum",
    name: "Some By Mi AHA BHA PHA 30 Days Miracle Serum",
    jpName: "サムバイミー AHA BHA PHA 30デイズ ミラクル セラム",
    description: "Sérum esfoliante com múltiplos ácidos. Remove células mortas, descongestiona poros e melhora a textura.",
    priceBRL: 110.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/bYKRX2jS/some-by-mi-aha-bha-pha.jpg",
    rating: 4.8,
    reviewsCount: 334,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 24
  },
  {
    id: "purito-deep-sea-watery-toner",
    name: "Purito Deep Sea Watery Toner",
    jpName: "プリート ディープシー ウォータリー トナー",
    description: "Tônico transparente com água marinha. Hidratação leve ideal para peles oleosas ou mistas.",
    priceBRL: 75.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8s0YkNCF/purito-watery-toner.jpg",
    rating: 4.9,
    reviewsCount: 298,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 26
  },
  {
    id: "benton-aloe-bha-skin-toner",
    name: "Benton Aloe BHA Skin Toner",
    jpName: "ベントン アロエ BHA スキン トナー",
    description: "Tônico esfoliante suave com BHA e aloe vera. Remove comedões sem agredir a pele sensível.",
    priceBRL: 65.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/G2h8vXBY/benton-aloe-bha-skin-toner.jpg",
    rating: 4.7,
    reviewsCount: 156,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 21
  },
  {
    id: "laneige-water-bank-hydro-mask",
    name: "Laneige Water Bank Hydro Mask",
    jpName: "ラネージュ ウォーターバンク ハイドロマスク",
    description: "Máscara noturna ultra hidratante. Acorda a pele mais macia, radiante e com brilho natural.",
    priceBRL: 145.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/Jz4FktXY/laneige-hydro-mask.jpg",
    rating: 4.9,
    reviewsCount: 523,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 32
  },
  {
    id: "hada-labo-gokujyun-premium-lotion",
    name: "Hada Labo Gokujyun Premium Lotion",
    jpName: "ハダラボ 極潤 プレミアム ローション",
    description: "Loção hidratante premium com ácido hialurônico de super penetração. Proporciona hidratação profunda em múltiplas camadas.",
    priceBRL: 125.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/L4vJ2j9k/hada-labo-premium-lotion.jpg",
    rating: 4.9,
    reviewsCount: 612,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 35
  },

  // --- CUIDADOS COM OS CABELOS ---

  {
    id: "mise-en-scene-perfect-serum-gold",
    name: "Mise en Scène Perfect Serum Gold Ouro",
    jpName: "ミーゼンシーン パーフェクト セラム ゴールド",
    description: "Versão premium com partículas de ouro e argan. Extremamente hidratante e reparador para cabelos danificados.",
    priceBRL: 165.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/VvGp73tV/mise-gold-serum.jpg",
    rating: 4.9,
    reviewsCount: 267,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 18
  },
  {
    id: "mise-en-scene-perfect-serum-damage-care",
    name: "Mise en Scène Perfect Serum Damage Care",
    jpName: "ミーゼンシーン パーフェクト セラム ダメージ ケア",
    description: "Fórmula específica para cabelos extremamente danificados. Repara, fortalece e restaura brilho.",
    priceBRL: 78.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/7Z4rQNQq/mise-damage-care-serum.jpg",
    rating: 4.8,
    reviewsCount: 198,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 22
  },
  {
    id: "kose-malisse-moist-shampoo",
    name: "Kosé Malisse Moist Shampoo",
    jpName: "コーセー マリッセ モイスト シャンプー",
    description: "Shampoo japonês hidratante para cabelos secos e ressecados. Com óleos e proteínas naturais.",
    priceBRL: 95.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/kose-malisse-shampoo.jpg",
    rating: 4.8,
    reviewsCount: 134,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 19
  },
  {
    id: "kose-malisse-moist-conditioner",
    name: "Kosé Malisse Moist Conditioner",
    jpName: "コーセー マリッセ モイスト コンディショナー",
    description: "Condicionador emparelhado ao shampoo. Hidrata profundamente e deixa os cabelos macios.",
    priceBRL: 95.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/kose-malisse-conditioner.jpg",
    rating: 4.8,
    reviewsCount: 128,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 18
  },
  {
    id: "shiseido-tsubaki-premium-moist-shampoo",
    name: "Shiseido Tsubaki Premium Moist Shampoo",
    jpName: "資生堂 TSUBAKI プレミアム モイスト シャンプー",
    description: "Shampoo premium da série clássica Tsubaki. Limpa suavemente mantendo a hidratação natural.",
    priceBRL: 85.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/3zGqT8hM/tsubaki-moist-shampoo.jpg",
    rating: 4.9,
    reviewsCount: 209,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 24
  },
  {
    id: "shiseido-tsubaki-premium-moist-conditioner",
    name: "Shiseido Tsubaki Premium Moist Conditioner",
    jpName: "資生堂 TSUBAKI プレミアム モイスト コンディショナー",
    description: "Condicionador que completa o tratamento do shampoo Tsubaki. Restaura o brilho e a maciez.",
    priceBRL: 85.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/3zGqT8hM/tsubaki-moist-conditioner.jpg",
    rating: 4.9,
    reviewsCount: 195,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 23
  },
  {
    id: "shiseido-tsubaki-premium-repair-mask",
    name: "Shiseido Tsubaki Premium Repair Mask",
    jpName: "資生堂 TSUBAKI プレミアム リペア マスク",
    description: "Máscara capilar intensiva da Tsubaki. Deixa cabelos extremamente macios e brilhantes em minutos.",
    priceBRL: 78.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/tsubaki-repair-mask.jpg",
    rating: 4.9,
    reviewsCount: 456,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 28
  },
  {
    id: "kose-segreta-collagen-shampoo",
    name: "Kosé Segreta Collagen Shampoo",
    jpName: "コーセー セグレタ コラーゲン シャンプー",
    description: "Shampoo com colágeno e ceramidas. Repara cabelos danificados e ressecados.",
    priceBRL: 88.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/L6q8y9vZ/kose-segreta-shampoo.jpg",
    rating: 4.7,
    reviewsCount: 112,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 20
  },
  {
    id: "kose-segreta-collagen-conditioner",
    name: "Kosé Segreta Collagen Conditioner",
    jpName: "コーセー セグレタ コラーゲン コンディショナー",
    description: "Condicionador com colágeno. Hidrata e fortalece os cabelos.",
    priceBRL: 88.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/L6q8y9vZ/kose-segreta-conditioner.jpg",
    rating: 4.7,
    reviewsCount: 108,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 19
  },
  {
    id: "pantene-gold-series-shampoo",
    name: "Pantene Gold Series Shampoo",
    jpName: "パンテーン ゴールド シリーズ シャンプー",
    description: "Shampoo com proteínas douradas. Deixa cabelos brilhantes e protegidos.",
    priceBRL: 65.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/pantene-gold-shampoo.jpg",
    rating: 4.6,
    reviewsCount: 87,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 25
  },
  {
    id: "pantene-gold-series-conditioner",
    name: "Pantene Gold Series Conditioner",
    jpName: "パンテーン ゴールド シリーズ コンディショナー",
    description: "Condicionador dourado para cabelos brilhantes e macios.",
    priceBRL: 65.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/pantene-gold-conditioner.jpg",
    rating: 4.6,
    reviewsCount: 82,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 24
  },
  {
    id: "dove-intensive-repair-shampoo",
    name: "Dove Intensive Repair Shampoo",
    jpName: "ダヴ インテンシブ リペア シャンプー",
    description: "Shampoo reparador com micronutrientes. Ideal para cabelos danificados.",
    priceBRL: 58.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/dove-intensive-repair-shampoo.jpg",
    rating: 4.6,
    reviewsCount: 94,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 26
  },
  {
    id: "dove-intensive-repair-conditioner",
    name: "Dove Intensive Repair Conditioner",
    jpName: "ダヴ インテンシブ リペア コンディショナー",
    description: "Condicionador que repara cabelos danificados profundamente.",
    priceBRL: 58.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/dove-intensive-repair-conditioner.jpg",
    rating: 4.6,
    reviewsCount: 88,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 25
  },
  {
    id: "lux-luminique-shampoo",
    name: "LUX Luminique Shampoo",
    jpName: "ラックス ルミニーク シャンプー",
    description: "Shampoo com brilho luminoso. Deixa cabelos com brilho intenso e saudável.",
    priceBRL: 72.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/lux-luminique-shampoo.jpg",
    rating: 4.7,
    reviewsCount: 125,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 21
  },
  {
    id: "lux-luminique-conditioner",
    name: "LUX Luminique Conditioner",
    jpName: "ラックス ルミニーク コンディショナー",
    description: "Condicionador luminoso que realça o brilho natural dos cabelos.",
    priceBRL: 72.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/8CvWMrq7/lux-luminique-conditioner.jpg",
    rating: 4.7,
    reviewsCount: 118,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 20
  },
  {
    id: "kanebo-freshel-hair-tonic",
    name: "Kanebo Freshel Hair Tonic",
    jpName: "カネボウ フレッシェル ヘア トニック",
    description: "Tônico capilar revigorador para o couro cabeludo. Estimula o crescimento e combate a queda.",
    priceBRL: 130.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/Hx4hDP0z/D-NQ-NP-2X-718348-MLA110637011648-052026-F.webp",
    rating: 4.8,
    reviewsCount: 165,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 22
  },
  {
    id: "fino-hair-oil",
    name: "Fino Hair Oil - Nutrição",
    jpName: "フィーノ プレミアム タッチ浸透美容液ヘアオイル",
    description: "Óleo capilar ultraleve que repara danos profundos, previne pontas duplas e dá brilho intenso.",
    priceBRL: 105.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/CKbvk62F/finetoday-fino-premium-touch-hair-oil-oleo-capilar-3.webp",
    rating: 4.9,
    reviewsCount: 290,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 35
  },
  {
    id: "fino-premium-touch-kit",
    name: "Kit Shampoo + Condicionador Fino Premium Touch",
    jpName: "フィーノ プレミアム タッチ シャンプー＆トリートメント",
    description: "Kit de limpeza e tratamento diário com a mesma tecnologia de reparação da famosa máscara Fino.",
    priceBRL: 179.90,
    serviceFeeBRL: 0,
    shippingEstBRL: 65.00,
    image: "https://i.postimg.cc/nV334m3v/D-NQ-NP-2X-758794-MLB81608717300-012025-F.webp",
    rating: 4.9,
    reviewsCount: 175,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 20
  },
  {
    id: "tsubaki-cool-repair-kit",
    name: "Kit Tsubaki Premium Cool & Repair (Azul)",
    jpName: "TSUBAKI プレミアム クール＆リペア ハンプセット",
    description: "Edição limitada refrescante (Cool) ideal para o verão. Limpa o couro cabeludo e repara danos.",
    priceBRL: 89.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 65.00,
    image: "https://i.postimg.cc/XYCx6z41/D-NQ-NP-2X-938804-CBT110708060883-042026-F-conjunto-de-shampoo-e-condicionador-shiseido-tsubaki-prem.webp",
    rating: 4.8,
    reviewsCount: 145,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 18
  },
  {
    id: "tsubaki-oil-force-m",
    name: "Óleo Capilar Tsubaki Oil Force M (Vermelho)",
    jpName: "TSUBAKI オイルフォース M",
    description: "Óleo capilar reparador de alta penetração da famosa linha Tsubaki. Protege do calor e dá maciez.",
    priceBRL: 118.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/Kcp5k2Y5/oleo-capilar-tsubaki-premium-camellia-1.webp",
    rating: 4.9,
    reviewsCount: 112,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 25
  },
  {
    id: "elizavecca-cer100-treatment",
    name: "Elizavecca CER-100 Collagen Ceramide Treatment",
    jpName: "エリザヴェッカ CER-100 コラーゲン セラミド",
    description: "O famoso 'desmaia cabelos' da caixinha ruiva. Tratamento de salão com colágeno e ceramidas para fios danificados.",
    priceBRL: 89.90,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/3WM4X9Vd/17.avif",
    rating: 4.9,
    reviewsCount: 890,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 45
  },
  {
    id: "lilyeve-grow-turn-ampoule",
    name: "Lilyeve Grow:Turn Ampoule",
    jpName: "Lilyeve グロウターン アンプル",
    description: "Ampola coreana para o couro cabeludo. Ajuda no crescimento, força capilar e combate à queda.",
    priceBRL: 160.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/s2Z2c5Pc/lil.webp",
    rating: 4.8,
    reviewsCount: 95,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 15
  },
  {
    id: "vt-pdrn-reedle-brush-serum",
    name: "VT Cosmetics PDRN + Reedle S Brush Hair Serum (100ml)",
    jpName: "VT PDRN リードル S ブラシヘアセラム",
    description: "Sérum capilar em bisnaga com escova de silicone embutida na ponta. Estimula e trata o couro cabeludo.",
    priceBRL: 154.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 40.00,
    image: "https://i.postimg.cc/XYtjppMV/sg-11134207-82609-ml660ai1v8xsbd.jpg",
    rating: 4.8,
    reviewsCount: 110,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 20
  },

  // --- HIGIENE E CUIDADOS PESSOAIS ---
  {
    id: "mofurashi-toothbrush",
    name: "Mofurashi Toothbrush",
    jpName: "モフラシ 歯ブラシ 特殊設計",
    description: "Escova de dentes especial ergonômica.",
    priceBRL: 120.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 25.00,
    image: "https://iili.io/C2KS5Cb.png",
    rating: 4.9,
    reviewsCount: 154,
    department: "Beleza, Higiene e Saúde",
    category: "Higiene e Cuidados Pessoais",
    stock: 50
  },
  {
    id: "femimore-glutathione-soap",
    name: "Femimore Glutathione Bubble Soap",
    jpName: "フェミモア グルタチオン バブルソープ",
    description: "Sabonete íntimo e corporal em espuma com Glutathione. Limpeza suave, controle de odor, oleosidade e clareamento leve.",
    priceBRL: 110.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/spChCy9L/50621-60-7f7bb7dbd3cd39bf13b37bcd7b35754b-1536x1024.jpg",
    rating: 4.8,
    reviewsCount: 64,
    department: "Beleza, Higiene e Saúde",
    category: "Higiene e Cuidados Pessoais",
    stock: 20
  },

  // --- APARELHOS ESTÉTICOS E TECNOLOGIA ---
  {
    id: "medicube-age-r-booster-pro",
    name: "Medicube Age-R Booster Pro",
    jpName: "メディキューブ 本格美顔器",
    description: "O dispositivo eletrônico facial inteligente que é um verdadeiro fenômeno na Coreia. Ele combina 4 tecnologias de clínica em um único aparelho (eletroporação, microcorrentes, EMS e LED) para abrir os caminhos da pele, fazendo com que seus séruns e cremes penetrem até 700% mais profundamente.",
    priceBRL: 1430.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 50.00,
    image: "https://i.postimg.cc/s2DtFdyK/medicube-age-r-booster-pro-device-pink.jpg",
    rating: 5.0,
    reviewsCount: 142,
    department: "Beleza, Higiene e Saúde",
    category: "Aparelhos Estéticos e Tecnologia",
    stock: 10
  },
  {
    id: "medicube-age-r-booster-pro-mini",
    name: "Medicube Age-R Booster Pro Mini",
    jpName: "メディキューブ 美顔器 ミニ",
    description: "A versão compacta, leve e ideal para viagens do famoso aparelho de eletroporação da Medicube. Focado em maximizar o brilho (glow) e a absorção dos seus produtos de skincare diários através de impulsos elétricos suaves e seguros.",
    priceBRL: 494.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.postimg.cc/qq0sY0Hn/d-nq-np-2x-881547-mlb83207883971-032025-f-medicube-age-r-booster-pro-mini-rosa-yloktw1oig.webp",
    rating: 4.9,
    reviewsCount: 86,
    department: "Beleza, Higiene e Saúde",
    category: "Aparelhos Estéticos e Tecnologia",
    stock: 15
  },
  {
    id: "portable-home-led-beauty-device",
    name: "Portable Home LED Beauty Device",
    jpName: "携帯用 LED 美顔器",
    description: "Aparelho estético portátil com terapia LED e massagem para uso doméstico (Compatível com PDRN e séruns).",
    priceBRL: 980.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 45.00,
    image: "https://i.postimg.cc/3Jc7cdx6/D-NQ-NP-2X-800111-MLB111755666986-062026-F.webp",
    rating: 4.9,
    reviewsCount: 52,
    department: "Beleza, Higiene e Saúde",
    category: "Aparelhos Estéticos e Tecnologia",
    stock: 10
  }
];

export default PRODUCTS;
