import type { Product } from './types';

// ⚠️ INSTRUÇÕES: Este arquivo DEVE estar em ./components/products.ts (não na raiz)
// Se o arquivo está em outro local, mova para ./components/products.ts

const PRODUCTS: Product[] = [
  // --- SKINCARE E TRATAMENTOS FACIAIS ---

  {
    id: "medicube-forever-cherry-ager-booster",
    name: "Medicube x Forever Cherry Age-R Booster (Edição Especial)",
    jpName: "Medicube x Forever Cherry Age-R Booster (Edição Especial)",
    description: "Dispositivo facial multifuncional com escova vibratória rosa em edição especial com laço. Ideal para limpeza profunda, esfoliação e melhor absorção de séruns.",
    priceBRL: 189.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/nsvDCqh4/Femimore-Glutathione-Bubble-Soap.jpg",
    rating: 5.0,
    reviewsCount: 12,
    department: "Beleza, Higiene e Saúde",
    category: "Acessórios e Dispositivos Estéticos",
    stock: 5
  },
  {
    id: "femimore-glutathione-bubble-soap",
    name: "Femimore Glutathione Bubble Soap",
    jpName: "Femimore Glutathione Bubble Soap",
    description: "Sabonete em espuma com Glutathione. Proporciona limpeza suave, ajuda no controle de oleosidade, odor e promove clareamento leve da pele.",
    priceBRL: 110.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/nsvDCqh4/Femimore-Glutathione-Bubble-Soap.jpg",
    rating: 4.7,
    reviewsCount: 45,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 20
  },
  {
    id: "mise-en-scene-perfect-serum-damage-care",
    name: "Mise en Scène Perfect Serum Damage Care",
    jpName: "Mise en Scène Perfect Serum Damage Care",
    description: "Sérum capilar coreano queridinho. Proporciona brilho intenso, hidratação, controle de frizz e proteção térmica aos fios.",
    priceBRL: 75.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/Mise-en-Sc-ne-Perfect-Serum-Damage-Care.jpg",
    rating: 4.9,
    reviewsCount: 182,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 15
  },
  {
    id: "mise-en-scene-perfect-serum-gold",
    name: "Mise en Scène Perfect Serum Gold (Ouro)",
    jpName: "Mise en Scène Perfect Serum Gold (Ouro)",
    description: "Sérum capilar premium com tecnologia de ouro para restauração profunda e brilho excepcional.",
    priceBRL: 85.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/gbtV0pxn/Mise-en-Sc-ne-Perfect-Serum-Gold-Ouro.webp",
    rating: 4.8,
    reviewsCount: 156,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados com o Cabelo",
    stock: 12
  },
  {
    id: "benton-aloe-bha-skin-toner",
    name: "Benton Aloe BHA Skin Toner",
    jpName: "Benton アロエ BHA スキン トナー",
    description: "Tônico coreano suave com Ácido Salicílico (BHA) e extrato de Aloe. Perfeito para limpar poros, controlar oleosidade e equilibrar o pH.",
    priceBRL: 119.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/ynTpn41z/Benton-Aloe-BHA-Skin-Toner.jpg",
    rating: 4.8,
    reviewsCount: 178,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 18
  },
  {
    id: "cosrx-advanced-snail-96-mucin",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    jpName: "COSRX アドバンスド スネイル 96 ムチン パワー",
    description: "Essência 96% de baba de caracol. Hidratação profunda, reparo de barreira cutânea e anti-inflamatório. Um bestseller coreano.",
    priceBRL: 129.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/r2L4RN0Z/COSRX-Advanced-Snail-96-Mucin-Power-Essence.jpg",
    rating: 4.9,
    reviewsCount: 523,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 25
  },
  {
    id: "isntree-hyaluronic-toner-plus",
    name: "ISNTREE Hyaluronic Toner Plus",
    jpName: "ISNTREE ヒアルロン トナー プラス",
    description: "Tônico potente com múltiplas formas de ácido hialurônico. Hidratação máxima e preparação ideal da pele.",
    priceBRL: 99.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/f7HSdnv/ISNTREE-Hyaluronic-Toner-Plus.jpg",
    rating: 4.9,
    reviewsCount: 267,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 20
  },
  {
    id: "hada-labo-gokujyun-premium-lotion",
    name: "Hada Labo Gokujyun Premium Lotion",
    jpName: "ハダラボ ゴクジュン プレミアム ローション",
    description: "Loção premium japonesa com ácido hialurônico de alto peso molecular. Hidratação transformadora e base perfeita para skincare.",
    priceBRL: 109.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/BVzFgWyw/Hada-Labo-Gokujyun-Premium-Lotion.webp",
    rating: 4.9,
    reviewsCount: 445,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 22
  },
  {
    id: "laneige-water-bank-hydro-mask",
    name: "Laneige Water Bank Hydro Mask",
    jpName: "Laneige ウォーターバンク ハイドロ マスク",
    description: "Máscara noturna de hidratação intensiva da Laneige. Restaura e regenera enquanto você dorme.",
    priceBRL: 189.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/tPWQqfY7/Laneige-Water-Bank-Hydro-Mask.webp",
    rating: 4.9,
    reviewsCount: 312,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 16
  },
  {
    id: "purito-deep-sea-watery-toner",
    name: "Purito Deep Sea Watery Toner",
    jpName: "Purito ディープシー ウォーティー トナー",
    description: "Tônico leve e hidratante com água profunda do mar. Textura refrescante, perfeita para clima tropical.",
    priceBRL: 89.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/QFXQQhSZ/Purito-Deep-Sea-Watery-Toner.jpg",
    rating: 4.8,
    reviewsCount: 198,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 19
  },
  {
    id: "purito-deep-sea-pure-water-cream",
    name: "Purito Deep Sea Pure Water Cream",
    jpName: "Purito ディープシー ピュア ウォーター クリーム",
    description: "Creme leve com água profunda do mar. Hidratação sem sensação oleosa, ideal para clima quente.",
    priceBRL: 119.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/23BRd40L/Purito-Deep-Sea-Pure-Water-Cream.jpg",
    rating: 4.8,
    reviewsCount: 187,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 17
  },
  {
    id: "pyunkang-yul-nutrition-cream",
    name: "Pyunkang Yul Nutrition Cream",
    jpName: "Pyunkang Yul ニュートリション クリーム",
    description: "Creme nutritivo coreano com ingredientes naturais. Perfeito para pele seca e sensível.",
    priceBRL: 129.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/N2mtLjRM/Pyunkang-Yul-Nutrition-Cream.avif",
    rating: 4.9,
    reviewsCount: 276,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 18
  },
  {
    id: "anti-signal-wrinkle-hunter-eye-cream",
    name: "Anti-Signal Wrinkle Hunter Eye Cream",
    jpName: "アンチシグナル リンクルハンター アイクリーム",
    description: "Creme japonês anti-rugas para olhos com Retinol e Niacinamida. Focado em reduzir linhas finas e melhorar a firmeza.",
    priceBRL: 99.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/Xf7XK324/Anti-Signal-Wrinkle-Hunter-Eye-Cream.jpg",
    rating: 4.7,
    reviewsCount: 64,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 25
  },
  {
    id: "some-by-mi-aha-bha-pha-30-serum",
    name: "Some By Mi AHA BHA PHA 30 Days Miracle Serum",
    jpName: "Some By Mi AHA BHA PHA 30 デイズ ミラクル",
    description: "Sérum esfoliante revolucionário coreano com 3 ácidos. Renova a pele, controla acne e melhora a textura.",
    priceBRL: 139.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/4RFcDgvh/Some-By-Mi-AHA-BHA-PHA-30-Days-Miracle-Serum.avif",
    rating: 4.8,
    reviewsCount: 334,
    department: "Beleza, Higiene e Saúde",
    category: "Skincare e Tratamentos Faciais",
    stock: 20
  },

  // --- CUIDADOS COM O CABELO ---

  {
    id: "kanebo-freshel-hair-tonic",
    name: "Kanebo Freshel Hair Tonic",
    jpName: "カネボウ フレッシェル ヘア トニック",
    description: "Tônico capilar revigorador para o couro cabeludo. Estimula o crescimento e combate a queda.",
    priceBRL: 130.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/ccMDW7tL/Kanebo-Freshel-Hair-Tonic.jpg",
    rating: 4.8,
    reviewsCount: 165,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 22
  },
  {
    id: "tsubaki-cool-repair-kit",
    name: "Kit Tsubaki Premium Cool & Repair (Azul)",
    jpName: "TSUBAKI プレミアム クール＆リペア ハンプセット",
    description: "Edição limitada refrescante (Cool) ideal para o verão. Limpa o couro cabeludo e repara danos.",
    priceBRL: 89.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 65.00,
    image: "https://i.ibb.co/Gv4kXQGx/Kit-Tsubaki-Premium-Cool-Repair-Azul.jpg",
    rating: 4.8,
    reviewsCount: 145,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 18
  },
  {
    id: "shiseido-tsubaki-premium-moist-shampoo",
    name: "Shiseido Tsubaki Premium Moist Shampoo",
    jpName: "資生堂 TSUBAKI プレミアム モイスト シャンプー",
    description: "Shampoo premium da linha Tsubaki com fórmula hidratante intensiva. Para cabelos ressecados e danificados.",
    priceBRL: 89.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/wNjrPxZZ/Shiseido-Tsubaki-Premium-Moist-Shampoo.webp",
    rating: 4.8,
    reviewsCount: 128,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 20
  },
  {
    id: "shiseido-tsubaki-premium-moist-conditioner",
    name: "Shiseido Tsubaki Premium Moist Conditioner",
    jpName: "資生堂 TSUBAKI プレミアム モイスト コンディショナー",
    description: "Condicionador premium da linha Tsubaki com fórmula hidratante intensiva. Complementa perfeitamente o shampoo.",
    priceBRL: 89.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/BVZKmDRC/Shiseido-Tsubaki-Premium-Moist-Conditioner.webp",
    rating: 4.8,
    reviewsCount: 125,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 20
  },
  {
    id: "shiseido-tsubaki-premium-repair-mask",
    name: "Shiseido Tsubaki Premium Repair Mask",
    jpName: "資生堂 TSUBAKI プレミアム リペア ヘアマスク",
    description: "Máscara capilar intensiva da Tsubaki para tratamento profundo de reparação em casa.",
    priceBRL: 79.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/mCC2dBXx/Shiseido-Tsubaki-Premium-Repair-Mask.webp",
    rating: 4.9,
    reviewsCount: 118,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 20
  },
  {
    id: "dove-intensive-repair-shampoo",
    name: "Dove Intensive Repair Shampoo",
    jpName: "Dove インテンシブ リペア シャンプー",
    description: "Shampoo intensivo reparador com proteína de leite. Combate ressecamento e danos severos.",
    priceBRL: 69.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/3yfVGY29/Dove-Intensive-Repair-Shampoo.webp",
    rating: 4.8,
    reviewsCount: 145,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 25
  },
  {
    id: "dove-intensive-repair-conditioner",
    name: "Dove Intensive Repair Conditioner",
    jpName: "Dove インテンシブ リペア コンディショナー",
    description: "Condicionador intensivo reparador para cabelos danificados. Restaura a hidratação e a maciez.",
    priceBRL: 69.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/fGpfvZ6S/Dove-Intensive-Repair-Conditioner.webp",
    rating: 4.8,
    reviewsCount: 142,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 25
  },
  {
    id: "lux-luminique-shampoo",
    name: "LUX Luminique Shampoo",
    jpName: "ラックス ルミニーク シャンプー",
    description: "Shampoo premium da LUX com cuidado luminoso. Dá brilho intenso e hidratação aos fios.",
    priceBRL: 75.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/jPZ1xhFJ/LUX-Luminique-Shampoo.webp",
    rating: 4.8,
    reviewsCount: 134,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 22
  },
  {
    id: "lux-luminique-conditioner",
    name: "LUX Luminique Conditioner",
    jpName: "ラックス ルミニーク コンディショナー",
    description: "Condicionador premium da LUX com cuidado luminoso. Complementa o shampoo para máximo brilho.",
    priceBRL: 75.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/BbfJ2wz/LUX-Luminique-Conditioner.jpg",
    rating: 4.8,
    reviewsCount: 131,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 22
  },
  {
    id: "pantene-gold-series-shampoo",
    name: "Pantene Gold Series Shampoo",
    jpName: "パンテーン ゴールド シリーズ シャンプー",
    description: "Shampoo premium Pantene com tecnologia de proteção e nutrição de ouro.",
    priceBRL: 65.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/8LRkWY4V/Pantene-Gold-Series-Shampoo.avif",
    rating: 4.7,
    reviewsCount: 156,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 28
  },
  {
    id: "pantene-gold-series-conditioner",
    name: "Pantene Gold Series Conditioner",
    jpName: "パンテーン ゴールド シリーズ コンディショナー",
    description: "Condicionador premium Pantene com tecnologia de proteção e nutrição de ouro.",
    priceBRL: 65.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/gFg01ytS/Pantene-Gold-Series-Conditioner.avif",
    rating: 4.7,
    reviewsCount: 153,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 28
  },
  {
    id: "kos-malisse-moist-shampoo",
    name: "Kos Malisse Moist Shampoo",
    jpName: "Kos マリース モイスト シャンプー",
    description: "Shampoo suave e hidratante para cabelos secos. Fórmula com proteínas naturais.",
    priceBRL: 59.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/cSv3Jymw/Kos-Malisse-Moist-Shampoo.webp",
    rating: 4.7,
    reviewsCount: 112,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 24
  },
  {
    id: "kos-malisse-moist-conditioner",
    name: "Kos Malisse Moist Conditioner",
    jpName: "Kos マリース モイスト コンディショナー",
    description: "Condicionador suave e hidratante para cabelos secos. Completa o cuidado de hidratação.",
    priceBRL: 59.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/mr2FRxZH/Kos-Malisse-Moist-Conditioner.png",
    rating: 4.7,
    reviewsCount: 109,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 24
  },
  {
    id: "kos-segreta-collagen-shampoo",
    name: "Kos Segreta Collagen Shampoo",
    jpName: "Kos セグレタ コラーゲン シャンプー",
    description: "Shampoo com colágeno para cabelos envelhecidos. Restaura firmeza e brilho.",
    priceBRL: 69.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/jZWsS6Cr/Kos-Segreta-Collagen-Shampoo.jpg",
    rating: 4.8,
    reviewsCount: 121,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 22
  },
  {
    id: "kos-segreta-collagen-conditioner",
    name: "Kos Segreta Collagen Conditioner",
    jpName: "Kos セグレタ コラーゲン コンディショナー",
    description: "Condicionador com colágeno para cabelos envelhecidos. Restaura e fortalece os fios.",
    priceBRL: 69.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/ycXbsQ7L/Kos-Segreta-Collagen-Conditioner.jpg",
    rating: 4.8,
    reviewsCount: 118,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 22
  },
  {
    id: "lilyeve-grow-turn-ampoule",
    name: "Lilyeve Grow:Turn Ampoule",
    jpName: "Lilyeve グロウターン アンプル",
    description: "Ampola coreana para o couro cabeludo. Ajuda no crescimento, força capilar e combate à queda.",
    priceBRL: 160.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/YFTNHX9s/Lilyeve-Grow-Turn-Ampoule.avif",
    rating: 4.8,
    reviewsCount: 95,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 15
  },
  {
    id: "vt-pdrn-reedle-brush-serum",
    name: "VT Cosmetics PDRN + Reedle S Brush Hair Serum (100ml)",
    jpName: "VT PDRN リードル S ブラシヘアセラム",
    description: "Sérum capilar em bisnaga com escova de silicone embutida na ponta. Estimula e trata o couro cabeludo.",
    priceBRL: 154.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 40.00,
    image: "https://i.ibb.co/Z6ykzckn/VT-Cosmetics-PDRN-Reedle-S-Brush-Hair-Serum-100ml.jpg",
    rating: 4.8,
    reviewsCount: 110,
    department: "Beleza, Higiene e Saúde",
    category: "Cuidados Capilares",
    stock: 20
  },

  // --- HIGIENE E CUIDADOS PESSOAIS ---
  {
    id: "femimore-glutathione-soap",
    name: "Femimore Glutathione Bubble Soap (Higiene Pessoal)",
    jpName: "フェミモア グルタチオン バブルソープ",
    description: "Sabonete íntimo e corporal em espuma com Glutathione. Limpeza suave, controle de odor, oleosidade e clareamento leve.",
    priceBRL: 110.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/nsvDCqh4/Femimore-Glutathione-Bubble-Soap.jpg",
    rating: 4.8,
    reviewsCount: 64,
    department: "Beleza, Higiene e Saúde",
    category: "Higiene e Cuidados Pessoais",
    stock: 20
  },
  {
    id: "medicube-red-cleansing-foam",
    name: "Medicube Red Cleansing Foam",
    jpName: "メディキューブ レッド クレンジング フォーム",
    description: "Espuma de limpeza premium vermelha da Medicube. Remove maquiagem, poluição e células mortas com suavidade.",
    priceBRL: 165.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/S7fGwWnn/Medicube-Red-Cleansing-Foam.avif",
    rating: 4.8,
    reviewsCount: 142,
    department: "Beleza, Higiene e Saúde",
    category: "Higiene e Cuidados Pessoais",
    stock: 17
  },

  // --- APARELHOS ESTÉTICOS E TECNOLOGIA ---
  {
    id: "medicube-age-r-booster-pro",
    name: "Medicube Age-R Booster Pro",
    jpName: "メディキューブ 本格美顔器",
    description: "O dispositivo eletrônico facial inteligente que é um verdadeiro fenômeno na Coreia. Ele combina 4 tecnologias de clínica em um único aparelho (eletroporação, microcorrentes, EMS e LED) para abrir os caminhos da pele, fazendo com que seus séruns e cremes penetrem até 700% mais profundamente.",
    priceBRL: 1430.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 50.00,
    image: "https://i.ibb.co/nsvDCqh4/Femimore-Glutathione-Bubble-Soap.jpg",
    rating: 5.0,
    reviewsCount: 142,
    department: "Beleza, Higiene e Saúde",
    category: "Aparelhos Estéticos e Tecnologia",
    stock: 10
  },
  {
    id: "medicube-age-r-booster-pro-mini",
    name: "Medicube Age-R Booster Pro Mini",
    jpName: "メディキューブ 美顔器 ミニ",
    description: "A versão compacta, leve e ideal para viagens do famoso aparelho de eletroporação da Medicube. Focado em maximizar o brilho (glow) e a absorção dos seus produtos de skincare diários através de impulsos elétricos suaves e seguros.",
    priceBRL: 494.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/nsvDCqh4/Femimore-Glutathione-Bubble-Soap.jpg",
    rating: 4.9,
    reviewsCount: 86,
    department: "Beleza, Higiene e Saúde",
    category: "Aparelhos Estéticos e Tecnologia",
    stock: 15
  },
  {
    id: "portable-home-led-beauty-device",
    name: "Portable Home LED Beauty Device",
    jpName: "携帯用 LED 美顔器",
    description: "Aparelho estético portátil com terapia LED e massagem para uso doméstico (Compatível com PDRN e séruns).",
    priceBRL: 980.00,
    serviceFeeBRL: 0,
    shippingEstBRL: 45.00,
    image: "https://i.ibb.co/nsvDCqh4/Femimore-Glutathione-Bubble-Soap.jpg",
    rating: 4.9,
    reviewsCount: 52,
    department: "Beleza, Higiene e Saúde",
    category: "Aparelhos Estéticos e Tecnologia",
    stock: 10
  }
];

export default PRODUCTS;
