import { Product, BlogPost } from "./types";

// 🪙 TAXAS DE CONVERSÃO DE MOEDA
export const YEN_TO_BRL_RATE = 0.035;

// 🛒 Catálogo de Produtos
export const PRODUCTS: Product[] = [
  // ==========================================
  // ITENS DE SKIN CARE
  // ==========================================
  {
    id: "senka-perfect-whip",
    name: "Senka Perfect Whip",
    jpName: "専科 パーフェクトホイップ",
    description: "Espuma de limpeza facial mais vendida do Japão. Cria uma espuma rica e cremosa que limpa profundamente sem ressecar a pele.",
    priceBRL: 54.90,
    serviceFeeBRL: 20.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/zTdKBgPN/51j8-UE-scr-L-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.9,
    reviewsCount: 245,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 30
  },
  {
    id: "keana-rice-pack",
    name: "Keana Rice Pack",
    jpName: "毛穴撫子 お米のパック",
    description: "Máscara facial de arroz japonês 100%. Auxilia no controle de poros, uniformiza o tom e deixa a pele mais lisa e iluminada.",
    priceBRL: 85.90,
    serviceFeeBRL: 25.00,
    shippingEstBRL: 40.00,
    image: "https://i.ibb.co/RTRdCfFq/new-collection-31-2.png",
    rating: 4.8,
    reviewsCount: 188,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 20
  },
  {
    id: "numbuzin-no9-mask",
    name: "Numbuzin No.9 Mask",
    jpName: "ナンバーズイン 9番 シートマスク",
    description: "Máscara lifting com NMN + 50 Peptídeos. Efeito firmador, melhora elasticidade e combate sinais de envelhecimento.",
    priceBRL: 65.90,
    serviceFeeBRL: 20.00,
    shippingEstBRL: 30.00,
    image: "https://i.ibb.co/35xTPT5B/61-Yvzp-Im-BGL.jpg",
    rating: 4.7,
    reviewsCount: 95,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 15
  },
  {
    id: "celimax-retinol-shot",
    name: "Celimax Retinol Shot Tightening Serum",
    jpName: "セリマックス レチノール美容液",
    description: "Sérum com Retinol que firma a pele, reduz linhas finas e melhora a textura.",
    priceBRL: 138.90,
    serviceFeeBRL: 35.00,
    shippingEstBRL: 45.00,
    image: "https://i.ibb.co/1Jbvy4fQ/D-Q-NP-711608-MLA104228285762-012026-F.webp",
    rating: 4.8,
    reviewsCount: 112,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 18
  },
  {
    id: "celimax-pore-brightening",
    name: "Celimax Pore Brightening Spot Care Cream",
    jpName: "セリマックス ブライトニングクリーム",
    description: "Creme clareador para poros e manchas com Niacinamida + Ácido Tranexâmico.",
    priceBRL: 112.90,
    serviceFeeBRL: 30.00,
    shippingEstBRL: 45.00,
    image: "https://i.ibb.co/S4BY3fL4/L-g0212699726-001.jpg",
    rating: 4.6,
    reviewsCount: 74,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 22
  },
  {
    id: "celimax-retinal-booster",
    name: "Celimax Retinal Shot Tightening Booster",
    jpName: "セリマックス レチナールブースター",
    description: "Booster potente com Retinal. Promove firmeza intensa e melhora rugas.",
    priceBRL: 128.90,
    serviceFeeBRL: 35.00,
    shippingEstBRL: 45.00,
    image: "https://i.ibb.co/99gRf3rD/D-NQ-NP-643899-MLA107452017338-032026-OO.jpg",
    rating: 4.9,
    reviewsCount: 130,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 14
  },
  {
    id: "refa-heart-comb-silver-gold",
    name: "ReFa Heart Comb (Silver/Gold)",
    jpName: "リファハートコーム シルバー/ゴールド",
    description: "Pente massajador capilar ReFa em formato de coração. Estimula o couro cabeludo, melhora a circulação e promove brilho e vitalidade aos fios.",
    priceBRL: 182.00,
    serviceFeeBRL: 45.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/KxZ54zJw/61-FK4n-NNLj-L-AC-SL1500.jpg",
    rating: 5.0,
    reviewsCount: 320,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 40
  },
  {
    id: "refa-heart-comb-red",
    name: "ReFa Heart Comb (Red)",
    jpName: "リファハートコーム レッド",
    description: "Pente massajador capilar ReFa em formato de coração na cor vermelha. Estimula o couro cabeludo, melhora a circulação e promove brilho e vitalidade aos fios.",
    priceBRL: 149.90,
    serviceFeeBRL: 40.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/CK50750k/pct-refa-heart-comb-aira-shinered-01.jpg",
    rating: 4.9,
    reviewsCount: 215,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 25
  },
  {
    id: "femimore-glutathione-soap",
    name: "Femimore Glutathione Bubble Soap",
    jpName: "フェミモア グルタチオン バブルソープ",
    description: "Sabonete em espuma com Glutathione. Limpeza suave, controle de oleosidade e clareamento leve.",
    priceBRL: 110.00,
    serviceFeeBRL: 25.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/spChCy9L/50621-60-7f7bb7dbd3cd39bf13b37bcd7b35754b-1536x1024.jpg",
    rating: 4.8,
    reviewsCount: 64,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 20
  },
  {
    id: "keshimin-cream-ex",
    name: "Keshimin Cream EX",
    jpName: "ケシミンクリームEX プレミアム処方",
    description: "Creme clareador premium para manchas com Vitamina C e Arbutin.",
    priceBRL: 120.00,
    serviceFeeBRL: 30.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/HfzGjNZY/kobayashi-keshimin-cream-ex-vitamin-c-arbutin-premium-formula-12g-with-cleaner-8015835-540x.jpg",
    rating: 4.9,
    reviewsCount: 142,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 15
  },
  {
    id: "aqualabel-special-gel",
    name: "Aqualabel Special Gel Cream",
    jpName: "アクアレーベル スペシャルジェルクリーム",
    description: "Creme gel hidratante para poros e pele madura.",
    priceBRL: 110.00,
    serviceFeeBRL: 25.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/NdZQncNF/2-1.png",
    rating: 4.7,
    reviewsCount: 198,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 25
  },
  {
    id: "beauty-of-joseon-eye-serum",
    name: "Beauty of Joseon Revive Eye Serum",
    jpName: "美女の朝鮮 まつ毛美容液 / アイセラム",
    description: "Sérum para olhos com Ginseng + Retinal. Reduz olheiras e rejuvenesce.",
    priceBRL: 99.00,
    serviceFeeBRL: 25.00,
    shippingEstBRL: 30.00,
    image: "https://i.ibb.co/5xjcBXN6/D-Q-NP-806727-MLU75555056272-042024-F.webp",
    rating: 4.8,
    reviewsCount: 310,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 18
  },
  {
    id: "numbuzin-no9-eye-cream",
    name: "Numbuzin No.9 Eye Cream",
    jpName: "ナンバーズイン 9番 アイクリーム",
    description: "Creme para olhos com NAD+ Retinal + 9 Peptídeos (formato seringa).",
    priceBRL: 179.90,
    serviceFeeBRL: 35.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/fGTP86Tt/1-14b4c7c5-d3e2-4855-858f-329212a9295e.png",
    rating: 4.9,
    reviewsCount: 87,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 12
  },
  {
    id: "anua-retinol-caffeine-eye",
    name: "Anua Retinol 0.1+ Caffeine Eye Cream",
    jpName: "アヌア レチノール カフェイン アイクリーム",
    description: "Creme para olhos com Retinol e Cafeína.",
    priceBRL: 179.90,
    serviceFeeBRL: 35.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/fdBJhbqw/12-68b2a521-8615-40c6-ad61-8d35e8ca10c0.png",
    rating: 4.8,
    reviewsCount: 104,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 16
  },
  {
    id: "seoul-1988-retinol-eye",
    name: "Seoul 1988 Retinol Eye Cream",
    jpName: "ソウル 1988 レチノール アイクリーム",
    description: "Creme para olhos com Retinol Lipossomo 4%.",
    priceBRL: 220.00,
    serviceFeeBRL: 45.00,
    shippingEstBRL: 40.00,
    image: "https://i.ibb.co/xttbpLcd/61wkxi21ot-L-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.7,
    reviewsCount: 52,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 10
  },
  {
    id: "anua-niacinamide-txa-serum",
    name: "Anua Niacinamide 10+ TXA 4 Dark Spot Serum",
    jpName: "アヌア ナイアシンアミド ダークスポットセラム",
    description: "Sérum anti-manchas com Niacinamida e Tranexâmico.",
    priceBRL: 118.00,
    serviceFeeBRL: 30.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/Ld8kGbdD/Serum-Niacinamida-10-TXA-4.png",
    rating: 4.9,
    reviewsCount: 165,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 22
  },
  {
    id: "anua-azelaic-cica-serum",
    name: "Anua Azelaic Acid 15+ Cica Serum",
    jpName: "アヌア アゼライン酸 シカセラム",
    description: "Sérum calmante com Ácido Azelaico 15% + Cica.",
    priceBRL: 179.90,
    serviceFeeBRL: 35.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/GNJ1qSc/Serum-Calmante-com-Acido-Azelaico-10-e-Acido-Hialuronico.png",
    rating: 4.8,
    reviewsCount: 119,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 14
  },
  {
    id: "rejuran-moisture-cream",
    name: "Rejuran Moisture Cream",
    jpName: "リジュラン モイスチャークリーム PDRN",
    description: "Creme com PDRN para hidratação e reparação da pele.",
    priceBRL: 129.00,
    serviceFeeBRL: 30.00,
    shippingEstBRL: 40.00,
    image: "https://i.ibb.co/3PRBHgg/3451128.jpg",
    rating: 4.9,
    reviewsCount: 138,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 19
  },
  {
    id: "biore-makeup-remover-oil",
    name: "Biore Makeup Remover Oil",
    jpName: "ビオレ メイク落とし クレンジングオイル",
    description: "Óleo removedor de maquiagem Biore.",
    priceBRL: 89.90,
    serviceFeeBRL: 20.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/4R4D5mJm/D-Q-NP-955266-MLA92278985694-092025-F.webp",
    rating: 4.8,
    reviewsCount: 420,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 35
  },

  // ==========================================
  // 💇‍♀️ SEÇÃO: HAIR CARE
  // ==========================================
  {
    id: "tsubaki-moist-repair-red",
    name: "Tsubaki Moist & Repair (Red)",
    jpName: "TSUBAKI モイスト＆リペア キット",
    description: "Kit Shampoo + Condicionador Moist & Repair.",
    priceBRL: 160.00,
    serviceFeeBRL: 40.00,
    shippingEstBRL: 65.00,
    image: "https://i.ibb.co/Vc4BKtBp/41o-PS-quar-L-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.9,
    reviewsCount: 280,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 15
  },
  {
    id: "tsubaki-volume-repair-yellow",
    name: "Tsubaki Premium Volume & Repair (Yellow)",
    jpName: "TSUBAKI ボリューム＆リペア キット",
    description: "Kit Shampoo + Condicionador Volume & Repair.",
    priceBRL: 59.90,
    serviceFeeBRL: 20.00,
    shippingEstBRL: 65.00,
    image: "https://i.ibb.co/q3tT4fHg/41x-M-SSU8x-L-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.8,
    reviewsCount: 340,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 25
  },
  {
    id: "tsubaki-damage-care-black",
    name: "Tsubaki Premium EX Damage Care (Black)",
    jpName: "TSUBAKI プレミアムEX ダメージケア",
    description: "Kit Shampoo + Condicionador EX Damage Care.",
    priceBRL: 80.00,
    serviceFeeBRL: 25.00,
    shippingEstBRL: 65.00,
    image: "https://i.ibb.co/gZnNpzT7/51v-XAUJ7-We-L-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.9,
    reviewsCount: 412,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 20
  },
  {
    id: "tsubaki-premium-cool-blue",
    name: "Tsubaki Premium Cool (Blue)",
    jpName: "TSUBAKI プレミアム クール スカルプ",
    description: "Kit Shampoo + Condicionador Cooling Sensation.",
    priceBRL: 169.00,
    serviceFeeBRL: 40.00,
    shippingEstBRL: 65.00,
    image: "https://i.ibb.co/cK9D6kbs/518v56f-Av-DL-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.7,
    reviewsCount: 94,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 12
  },
  {
    id: "tsubaki-hair-oil-force-m",
    name: "Tsubaki Hair Oil Force M",
    jpName: "TSUBAKI ヘアオイル フォースM",
    description: "Óleo capilar reparador Tsubaki.",
    priceBRL: 120.00,
    serviceFeeBRL: 30.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/wZ8Hy17C/61-Q-CNb-FY9-L-AC-UF1000-1000-QL80-FMwebp-Dp-Weblab.webp",
    rating: 4.9,
    reviewsCount: 156,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 18
  },
  {
    id: "lilyeve-grow-turn-ampoule",
    name: "Lilyeve Grow:Turn Ampoule",
    jpName: "リリイブ グロウターン アンプル",
    description: "Ampola capilar para couro cabeludo anti-queda e crescimento.",
    priceBRL: 110.00,
    serviceFeeBRL: 25.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/z1Ts4k2/D-Q-NP-703390-CBT104372071678-012026-F.webp",
    rating: 4.6,
    reviewsCount: 43,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 15
  },
  {
    id: "vt-cosmetics-pdrn-needle-hair",
    name: "VT Cosmetics PDRN+ Needle S Brush Hair Serum",
    jpName: "VT コスメティックス PDRN ニードル ヘアセラム",
    description: "Sérum capilar com PDRN para couro cabeludo.",
    priceBRL: 73.00,
    serviceFeeBRL: 20.00,
    shippingEstBRL: 35.00,
    image: "https://i.ibb.co/ccckHd4T/71c-KBPGme-WL-AC-UF1000-1000-QL80-FMwebp-Dp-Weblab.webp",
    rating: 4.8,
    reviewsCount: 72,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 22
  },

  // ==========================================
  // 🛍️ SEÇÃO: ACESSÓRIOS
  // ==========================================
  {
    id: "sheglam-brow-brush",
    name: "Sheglam Brow Brush & Dip",
    jpName: "シーグラム ブロウブラシ＆ディップ",
    description: "Lápis + escova para sobrancelhas (Taupe).",
    priceBRL: 160.00,
    serviceFeeBRL: 40.00,
    shippingEstBRL: 30.00,
    image: "https://i.ibb.co/TMZfCTb7/51t-I64-y-KJL-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.5,
    reviewsCount: 118,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 30
  },
  {
    id: "medicube-booster-pro",
    name: "Medicube Booster Pro",
    jpName: "メディキューブ 美顔器 ブースタープロ",
    description: "Dispositivo facial Medicube Booster Pro.",
    priceBRL: 146.00,
    serviceFeeBRL: 35.00,
    shippingEstBRL: 50.00,
    image: "https://i.ibb.co/ksMxWzbF/1-bbd45f2b-c684-4b30-ab4d-1e7c3384e254.png",
    rating: 5.0,
    reviewsCount: 65,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 8
  },
  {
    id: "traen-230-hair-removal",
    name: "TraEn 230 Hair Removal Tool",
    jpName: "TraEn 230 脱毛器 フェイス＆ボディ",
    description: "Removedor de pelos facial / corporal.",
    priceBRL: 90.00,
    serviceFeeBRL: 25.00,
    shippingEstBRL: 40.00,
    image: "https://i.ibb.co/cK9D6kbs/518v56f-Av-DL-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.6,
    reviewsCount: 39,
    department: "Beleza, Higiene e Saúde",
    category: "Maquiagem e cuidados com o cabelo",
    stock: 14
  },
  {
    id: "mofurashi-toothbrush",
    name: "Mofurashi Toothbrush",
    jpName: "モフラシ 歯ブラシ 特殊設計",
    description: "Escova de dentes especial ergonômica.",
    priceBRL: 55.00,
    serviceFeeBRL: 30.00,
    shippingEstBRL: 25.00,
    image: "https://i.ibb.co/KgRprTR/61sa9-Ojx3-JL-AC-UF1000-1000-QL80-FMwebp.webp",
    rating: 4.9,
    reviewsCount: 154,
    department: "Beleza, Higiene e Saúde",
    category: "Higiene, cuidados bucais e produtos para banho",
    stock: 50
  }
];

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Gustavo Barboza",
    role: "Cliente Suíte #1292",
    comment: "Excelente serviço de redirecionamento! Minha caixa chegou de Mie até o interior de SP em 11 dias via EMS. Caixa muito bem embalada e protegida.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80"
  },
  {
    id: "2",
    name: "Mariana Silva",
    role: "Compradora Skincare",
    comment: "Estava com medo das taxas de importação atuais, mas o checkout calculou tudo certinho e chegou direto na minha porta sem nenhuma cobrança extra.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80"
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "post-1",
    title: "Como funciona o Envio Consolidado de caixas do Japão para o Brasil?",
    excerpt: "Entenda o passo a passo de como juntar suas compras feitas em lojas diferentes no nosso armazém em Mie e economizar até 60% no frete internacional.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
    date: "15 Mai, 2026",
    readTime: "5 min de leitura",
    category: "Guias de Importação"
  },
  {
    id: "post-2",
    title: "Os 5 Skincares Japoneses que são febre absoluta em 2026",
    excerpt: "Descubra os detalhes tecnológicos por trás de marcas consagradas como Bioré, Hada Labo e Shiseido Fino e saiba por que a rotina de beleza japonesa é insuperável.",
    image: "https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&w=600&q=80",
    date: "10 Mai, 2026",
    readTime: "4 min de leitura",
    category: "Tendências & Cosméticos"
  }
];
